image: zacharyfoster/pathogensurveillance-workshop:0.9

tasks:
  - name: Initialize conda 
    command: |
      conda init bash
      source ${HOME}/.bashrc
      conda activate qc
      clear
      
vscode:
  extensions:
    - anwar.papyrus-pdf
    - ritwickdey.liveserver
    
